name: Test PR

on:
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements-dev.txt
        pip install "sqlalchemy<1.4"
    - name: Run tests < sqlalchemy1.4
      run: |
        nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
        export PYTHONPATH=.:$PYTHONPATH
        python examples/activerecord.py
        python examples/all_features.py
        python examples/eagerload.py
        python examples/repr.py
        python examples/smartquery.py
        python examples/serialize.py
        python examples/timestamp.py
    - name: Run tests >= sqlalchemy1.4
      run: |
        pip install -U sqlalchemy
        nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
        export PYTHONPATH=.:$PYTHONPATH
        python examples/activerecord.py
        python examples/all_features.py
        python examples/eagerload.py
        python examples/repr.py
        python examples/smartquery.py
        python examples/serialize.py
        python examples/timestamp.py