name: Test PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements-dev.txt
    - name: Run tests with sqlalchemy current
      run: |
        nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
        export PYTHONPATH=.:$PYTHONPATH
        python examples/activerecord.py
        python examples/all_features.py
        python examples/eagerload.py
        python examples/repr.py
        python examples/smartquery.py
        python examples/serialize.py
        python examples/timestamp.py
    - name: Run tests with sqlalchemy next
      run: |
        pip install --upgrade sqlalchemy --pre
        nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
        export PYTHONPATH=.:$PYTHONPATH
        python examples/activerecord.py
        python examples/all_features.py
        python examples/eagerload.py
        python examples/repr.py
        python examples/smartquery.py
        python examples/serialize.py
        python examples/timestamp.py